spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.99.100:5432/deal
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
  kafka:
    bootstrap-servers: 192.168.99.100:29092
  mail:
    host: smtp.gmail.com
    port: 587
    username: arsshvets@gmail.com
    password: ldvhrrwidpnkxumq
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  swagger-ui:
    path: /dossier/swagger-ui.html
  api-docs:
    path: /dossier/api-docs

server:
  error:
    include-message: always
  port: 8050

logging:
  level:
    root: INFO
    ru.senya.deal: TRACE
